
variables:
  ORD_SOUMET_CPUS: "4"
  ORD_SOUMET_M: "8G"
  ORD_SOUMET_TMPFS: "4096"
  doc_install_dir: "/home/spst900/public_html/fstpy/${CI_BUILD_REF_NAME}"
  latest_doc_install_dir: "/home/spst900/public_html/fstpy/latest"
  deploy_dir_prefix: /fs/site5/eccc/cmd/w/spst900/spooki/CI_fstpy/${CI_BUILD_REF_NAME}
  ssm_dir_prefix: /space/hall5/sitestore/eccc/cmd/s/sgci800/ci_ssm_dir/fstpy


stages:
  - run_unittest
  - run_regtests
  - make_doc
  - install_doc
  - ssm_package
  - deploy
  - keep_ssm_package
  - cascade

workflow:
  rules:
    # This rule will allow all push events (including all branches and tags), trigger events (token), web events (manual pipeline), API and pipeline (multi-project pipelines).
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "pipeline"'


# default:
# when 'default' becomes supported, uncomment the above line, delete this line, and indent the before_script part.
before_script:
  - . /fs/ssm/eccc/mrd/ordenv/20240916/profile/ord
  - . r.load.dot eccc/mrd/rpn/MIG/ENV/rpnpy/2.2.0 eccc/mrd/rpn/code-tools/ENV/cdt-1.6.6/SCIENCE/inteloneapi-2022.1.2
  - . r.load.dot eccc/mrd/rpn/libs/20230906 eccc/cmd/cmda/libs/20230906/inteloneapi-2022.1.2
  - . r.load.dot cmo/cmoi/base/20240405
  - . ssmuse-sh -p /fs/ssm/eccc/cmd/cmds/env/python/py310_2023.07.28_all
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/apps/ci_fstcomp/202501/00
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/cmcdict/202503/00

run_unittest:
  stage: run_unittest
  script:
    # - sleep 2000
    - cd test
    - python3 -m pytest -vrf -m unit_tests


run_regtests:
  stage: run_regtests
  script:
    - cd test
    - python3 -m pytest -vrf -m regressions

make_doc:
  stage: make_doc
  script:
    - cd doc
    - make doc
  artifacts:
    paths:
      - doc/_build/html


install_doc:
  stage: install_doc
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - rm -rf ${doc_install_dir}
    - mkdir -p ${doc_install_dir}
    - cp -r ${cdir}/* ${doc_install_dir}
    - echo "Installed in ${doc_install_dir}"
    - echo "Visit http://web.science.gc.ca/~spst900/fstpy/${CI_BUILD_REF_NAME}"

install_latest_doc:
  stage: install_doc
  rules:
    # only on master
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - rm -rf ${latest_doc_install_dir}
    - mkdir -p ${latest_doc_install_dir}
    - cp -r ${cdir}/* ${latest_doc_install_dir}
    - echo "Installed in ${latest_doc_install_dir}"
    - echo "Visit http://web.science.gc.ca/~spst900/fstpy/latest"


ssm_package:
  stage: ssm_package
  script:
    - cd livraison
    - DEPLOY_DIR=${deploy_dir_prefix}/${CI_PIPELINE_ID}
    - echo ${DEPLOY_DIR}
    - ./make_ssm_package.py --install --temp ${DEPLOY_DIR}
  artifacts:
    expire_in: 1 hrs
    paths:
      - livraison/

deploy:
  stage: deploy
  rules:
    # only on master
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - cd ${deploy_dir_prefix}
    - rm -f latest
    - ln -s ${CI_PIPELINE_ID} latest

remove_ssm:
  stage: deploy
  rules:
    # on all branch other than master
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
  script:
    - rm -r ${deploy_dir_prefix}

keep_ssm_package:
  stage: keep_ssm_package
  rules:
    - if: '$CI_COMMIT_TAG =~ /^r-\d+\.\d+\.\d+/'
  script:
    - cd livraison
    - cp *.ssm ${ssm_dir_prefix}/
    - echo "Your package is here ${ssm_dir_prefix}"

cascade:
  stage: cascade
  rules:
    # only on master
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    FSTPY_TRIGGER: ${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}:${CI_BUILD_REF}
  inherit:
    variables: false # do not send all the global variables to the triggered pipeline
  trigger:
    project: cmdw-spooki/spookipy
    branch: master
