[project]
name = "fstpy-tests"
description = "Test environments for fstpy"
authors = ["Yordan Radev <yordan.radev@ec.gc.ca>"]
channels = ["fortiers", "conda-forge", "nodefaults"]
platforms = ["linux-64"]

[tasks]
tests = "python test_fstpy.py"


[dependencies]

[feature.py38.dependencies]
python = "3.8.*"
fstpy = ">=2025.3.0"

[feature.py313.dependencies]
python = "3.13.*"
fstpy = ">=2025.3.0"

[environments]
py38 = ["py38"]
py313 = ["py313"] 
